def generate_report(
    topic,
    research_result,
    report_type,
    depth
):
    """
    Compatibility wrapper.

    The actual report is now generated by
    the single CrewAI research task.

    This function does NOT call an LLM.
    """

    return str(
        research_result
    )
